title: "JIANG Mingyuan / Academic Portfolio"
author:
  name: "JIANG Mingyuan"
  email: "m.y.jiang@polyu.edu.hk"
github: "jiangmy97"
bio: "Research Assistant Professor in Electrical and Electronic Engineering at PolyU"
location: "Hong Kong"
employer: "The Hong Kong Polytechnic University"
